services:
  - type: web
    name: whatsapp-headless
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: PORT
        value: "3000"
